import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { ConfigProvider } from "./contexts/ConfigContext";
import AnalyticsTracker from "./admin/analytics/AnalyticsTracker";
import Breadcrumb from "./components/Breadcrumb";
import { Testimonials } from "./components/Testimonials";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CSM Aviation",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider>
          <Header />
          {/* <div className="container mx-auto px-4 py-4"> */}
          <Breadcrumb />
          {/* </div> */}
          <main>{children}
            <Analytics />
            <SpeedInsights />
            <AnalyticsTracker />
          </main>
          <Testimonials />
          <Footer />
        </ConfigProvider>
      </body>
    </html>
  );
}