// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayoutContent from "./components/ClientLayoutContent";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/react"


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "CSM Aviation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header headerColor={"#bdae7a"} />
        <main>{children}
          <Analytics />
        </main>
        <Footer />
      </body>
    </html>
  );
}
